### PR TITLE
feature: Set the vision image orientation to compensate compare to t…

### PR DESCRIPTION
**Pull request by Valentin-Rault**
…he frame orientation

### CODE REVIEW

**Review by pepperav — APPROVED** [review]
Tested and it works!

react-native 0.74.3
react-native-vision-camera 4.4.1

**Comment by Valentin-Rault** [comment]
@ismaelsousa how is this PR looking? Is there something I can do to have it merged?

**Comment by ismaelsousa** [comment]
@Valentin-Rault Thanks for helping us I plan to test it today and release it :)

**Comment by Valentin-Rault** [comment]
Perfect, thank you for the quick response :)

**Comment by ismaelsousa** [comment]
just to keep you updated, I am trying to do the rotation in another way

**Comment by dragonlobster** [comment]
no matter which way i hold my iPad, the OCR detects text only if i turn the text 90 degrees. I am wondering if this PR solves the problem, or is there some way to match the preview orientation of Vision Camera with the frame orientation for OCR? Thanks

**Comment by ismaelsousa** [comment]
@dragonlobster could you try it using this branch?

**Comment by Valentin-Rault** [comment]
Which version of react native vision camera are you using?
In the version I noted in the description, the frame is not oriented correctly and that has been fixed in 4.4.2. I haven't tried the latest version though

**Comment by nathangabriel27** [comment]
Same problem
    "react-native": "^0.73.6",
    "react-native-vision-camera": "^4.3.1",
    "@ismaelmoreiraa/vision-camera-ocr": "^3.0.1",
    
Any idea for a solution?

**Comment by alamothe** [comment]
Are there any updates?

**Comment by ismaelsousa** [comment]
I planned to translate the outputs for the right rotation. 
But if that's work for you I'll merge it and release as pre-release

**Comment by ismaelsousa** [comment]
@Valentin-Rault @dragonlobster @nathangabriel27 @alamothe 

https://www.npmjs.com/package/@ismaelmoreiraa/vision-camera-ocr/v/3.0.2-0

**Comment by ismaelsousa** [comment]
if it is not please submit a new PR I didn't test it

**Comment by ismaelsousa** [comment]
if it's worked fine please let me know it

**Comment by DaBs** [comment]
@ismaelsousa We've tested it and can confirm it fixes the portrait problem at least.

**Comment by nathangabriel27** [comment]
Tested and working correctly, Android and IOS.

**Comment by mingca** [comment]
Does this fix Android? I am still having same issue in Android with version 3.0.2. My app is landscape locked app but the camera preview is 90 degree off and displaying as portrait mode.

**Comment by mingca** [comment]
> Tested and working correctly, Android and IOS.

@nathangabriel27 Does this work for Android for you?

**Comment by ismaelsousa** [comment]
@mingca Hmm, that's interesting. In v4 of Vision, I had to patch it because it's initialized as portrait in the display orientation and never gets updated. I am not sure what version are you using but you can see this patch here

```
diff --git a/android/src/main/java/com/mrousavy/camera/core/OrientationManager.kt b/android/src/main/java/com/mrousavy/camera/core/OrientationManager.kt
index 5326d6bd4fc11b6d0adf20f481f2576835103c8b..8040da208bdac6287eb1d15d74777b786fa32c9c 100644
--- a/android/src/main/java/com/mrousavy/camera/core/OrientationManager.kt
+++ b/android/src/main/java/com/mrousavy/camera/core/OrientationManager.kt
@@ -3,6 +3,7 @@ package com.mrousavy.camera.core
 import android.content.Context
 import android.hardware.display.DisplayManager
 import android.util.Log
+import android.view.Display
 import android.view.OrientationEventListener
 import android.view.Surface
 import com.mrousavy.camera.core.types.Orientation
@@ -18,8 +19,8 @@ class OrientationManager(private val context: Context, private val callback: Cal
   private var lastPreviewOrientation: Orientation? = null
 
   // Screen Orientation Listener
-  private var screenRotation = Surface.ROTATION_0
   private val displayManager = context.getSystemService(Context.DISPLAY_SERVICE) as DisplayManager
+  private var screenRotation = displayManager.getDisplay(Display.DEFAULT_DISPLAY).rotation
   private val displayListener = object : DisplayManager.DisplayListener {
     override fun onDisplayAdded(displayId: Int) = Unit
     override fun onDisplayRemoved(displayId: Int) = Unit

```

**Pull request merged**
