### PR TITLE
fix(ios): export like docs

### PR DESCRIPTION
**Pull request by danieloprado**
Maybe fix https://github.com/aarongrider/vision-camera-ocr/pull/32 IOS 3.9 build, I couldn't test in a real device.

Based on https://react-native-vision-camera.com/docs/guides/frame-processors-plugins-ios swift tab.

### CODE REVIEW

**Comment by ismaelsousa** [comment]
@danieloprado thanks for this, I tried, but it is not working.

But please check the latest version I fixed the lib when using the vision camera 3.9.0

**Comment by tomhopkins** [comment]
Apoloiges if posting in the wrong place. I'm getting this in build (expo):

`[FrameProcessorPluginRegistry addFrameProcessorPlugin:@"scanOCR" withInitializer:^FrameProcessorPlugin * _Nonnull(NSDictionary * _Nullable options) {
> 15 |         return [[OCRFrameProcessorPlugin alloc] initWithOptions:options];
     |                                                 ^ no visible @interface for 'OCRFrameProcessorPlugin' declares the selector 'initWithOptions:'`

**Comment by ismaelsousa** [comment]
@tomhopkins is this happening in the latest version?

**Comment by ismaelsousa** [comment]
I added the proxy option on the latest, could u try it?

**Comment by tomhopkins** [comment]
Yes, latest versions I think 

"dependencies": {
    "@expo/config-plugins": "~7.8.0",
    "@gorhom/bottom-sheet": "^4.5.1",
    "@ismaelmoreiraa/vision-camera-ocr": "^2.3.0",
    ...
    "@xstate/react": "^4.0.2",
    "expo": "^50.0.7",
    ...
    "expo-av": "~13.10.5",
    "expo-build-properties": "~0.11.1",
    ...
    "expo-updates": "~0.24.10",
    ...
    "npm": "^10.4.0",
    "react": "18.2.0",
    ...
    "react-native": "0.73.4",
    ...
    "react-native-vision-camera": "^3.9.0",
    ...
"react-native-worklets-core": "0.3.0",
    ...
  },


Sorry, what would the proxy do?

**Comment by ismaelsousa** [comment]
@tomhopkins Somehow, my changes were not included, let me patch again

**Comment by ismaelsousa** [comment]
@tomhopkins bump to  2.3.1

**Comment by ismaelsousa** [comment]
this proxy initialize https://github.com/ismaelsousa/vision-camera-ocr/compare/2.3.0...2.3.1

**Comment by tomhopkins** [comment]
Trying now, thanks

**Comment by tomhopkins** [comment]
Thanks. We're in business :-).

**Pull request closed without merging**
